/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import code.Decodificador;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author junio
 */
public class Main extends javax.swing.JFrame {

    public FileNameExtensionFilter filter = new FileNameExtensionFilter("Código Fonte ULA", "ula", "ULA");
    private File arqUla = null;
    private final Decodificador decoder = new Decodificador();

    public Main() {
        initComponents();
        ArqChooser.setFileFilter(filter);
        ArqChooser.setMultiSelectionEnabled(false);
        ArqChooser.setDialogTitle("Escolha o arquivo ULA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArqChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        escArquivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        compilar = new javax.swing.JButton();
        txtArq = new javax.swing.JLabel();
        nameArq = new javax.swing.JTextField();
        txtArqHex = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtComp = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fecharBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        ArqChooser.setAcceptAllFileFilterUsed(false);
        ArqChooser.setFileFilter(null);
        ArqChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArqChooserActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decodificador ULA - HEX");
        setForeground(new java.awt.Color(176, 224, 230));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(176, 224, 230));
        jPanel2.setForeground(new java.awt.Color(176, 224, 230));
        jPanel2.setAutoscrolls(true);

        escArquivo.setBackground(new java.awt.Color(51, 51, 51));
        escArquivo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        escArquivo.setForeground(new java.awt.Color(255, 255, 255));
        escArquivo.setText("📁");
        escArquivo.setBorderPainted(false);
        escArquivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        escArquivo.setFocusPainted(false);
        escArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escArquivoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Compile arquivos .ula em .hex");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Escolha um arquivo ULA:");

        compilar.setBackground(new java.awt.Color(51, 51, 51));
        compilar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        compilar.setForeground(new java.awt.Color(255, 255, 255));
        compilar.setText("📃");
        compilar.setBorderPainted(false);
        compilar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        compilar.setEnabled(false);
        compilar.setFocusPainted(false);
        compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compilarActionPerformed(evt);
            }
        });

        txtArq.setBackground(new java.awt.Color(0, 0, 0));
        txtArq.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtArq.setForeground(new java.awt.Color(0, 0, 0));
        txtArq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtArq.setText("Arquivo: ");

        nameArq.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameArq.setEnabled(false);

        txtArqHex.setBackground(new java.awt.Color(0, 0, 0));
        txtArqHex.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtArqHex.setForeground(new java.awt.Color(0, 0, 0));
        txtArqHex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtArqHex.setText("Nome do arquivo HEX:");
        txtArqHex.setToolTipText("");
        txtArqHex.setEnabled(false);

        txtComp.setBackground(new java.awt.Color(0, 0, 0));
        txtComp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtComp.setForeground(new java.awt.Color(0, 0, 0));
        txtComp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtComp.setText("Compilar:");
        txtComp.setEnabled(false);

        txtStatus.setBackground(new java.awt.Color(0, 0, 0));
        txtStatus.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(0, 0, 0));
        txtStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatus.setToolTipText("");
        txtStatus.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(compilar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(escArquivo)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nameArq, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addComponent(jSeparator2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArqHex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtComp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArq)
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArqHex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setAutoscrolls(true);

        fecharBtn.setBackground(new java.awt.Color(51, 51, 51));
        fecharBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fecharBtn.setForeground(new java.awt.Color(255, 255, 255));
        fecharBtn.setText("❌");
        fecharBtn.setBorderPainted(false);
        fecharBtn.setContentAreaFilled(false);
        fecharBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fecharBtn.setFocusPainted(false);
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Decodificador ULA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecharBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fecharBtnActionPerformed

    private void escArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escArquivoActionPerformed
        try {
            int val = ArqChooser.showOpenDialog(this);
            if (val == JFileChooser.APPROVE_OPTION) {
                txtArqHex.setEnabled(true);
                txtComp.setEnabled(true);
                nameArq.setEnabled(true);
                compilar.setEnabled(true);
                arqUla = ArqChooser.getSelectedFile();
                txtArq.setText("Arquivo: " + arqUla.getName());
            } else {
                txtArqHex.setEnabled(false);
                txtComp.setEnabled(false);
                nameArq.setEnabled(false);
                compilar.setEnabled(false);
                txtArq.setText("Arquivo:");
                txtStatus.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_escArquivoActionPerformed

    private void compilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compilarActionPerformed
        try {
            String status = decoder.compileCode(nameArq.getText(),arqUla);
            txtStatus.setText(status);
            if (status.contains("sucesso")) {
                JOptionPane.showMessageDialog(this, "Arquivo compilado com sucesso \n" + status, "Compilação completa", JOptionPane.INFORMATION_MESSAGE);
                txtStatus.setForeground(Color.black);
                if (JOptionPane.showConfirmDialog(this, "Deseja enviar o arquivo compilado para o arduino processar?", "Enviar HEX para arduíno", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == 0) {
                    try {
                        Runtime.getRuntime().exec("cmd /c start " + new File("comunicadorSerial.exe").getPath() + " " + (!nameArq.getText().equals("") ? nameArq.getText() + ".hex" : arqUla.getName().replace(".ula", "") + ".hex"));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Erro desconhecido na comunicação:\n" + e.getMessage(), "Erro desconhecido no sistema de envio", JOptionPane.ERROR_MESSAGE);
                        e.printStackTrace();
                    }
                }
                nameArq.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Erro: " + status, "Erro", JOptionPane.ERROR_MESSAGE);
                txtStatus.setForeground(Color.red);
                nameArq.setText("");
                nameArq.setEnabled(false);
                compilar.setEnabled(false);
                txtArqHex.setEnabled(false);
                txtComp.setEnabled(false);
                txtArq.setText("Arquivo:");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_compilarActionPerformed

    private void ArqChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArqChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArqChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ArqChooser;
    private javax.swing.JButton compilar;
    private javax.swing.JButton escArquivo;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameArq;
    private javax.swing.JLabel txtArq;
    private javax.swing.JLabel txtArqHex;
    private javax.swing.JLabel txtComp;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
